# Generated by Django 2.2.10 on 2024-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('activity_name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('vacancy', models.IntegerField()),
                ('type', models.CharField(max_length=128)),
                ('theme', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('resources', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_id', models.IntegerField()),
                ('destination_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
