# Generated by Django 4.2.5 on 2024-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='created',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='text',
        ),
        migrations.AddField(
            model_name='activity',
            name='peo_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
