# Generated by Django 4.2.5 on 2024-03-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='coasts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
